apiVersion: apps/v1
kind: Deployment
metadata:
  name: po-tool-be-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: po-tool-be-api
  template:
    metadata:
      labels:
        app: po-tool-be-api
    spec:
      containers:
      - image: okteto/po-tool-be-api:node
        name: po-tool-be-api

---

apiVersion: v1
kind: Service
metadata:
  name: po-tool-be-api
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "po-tool-be-api"
    port: 3000
  selector:
    app: po-tool-be-api
